Support the future parser - make 'order' default to a string
datacat's 'order' parameter is actually a string (defaulting to "50") and
having a default which is an integer causes the following error on Puppet 3.8.7
with the future parser enabled.

  Error: /Stage[main]/Goaudit::Config/Datacat[/etc/go-audit.yaml]/Datacat_collector[/etc/go-audit.yaml]: Could not evaluate: comparison of Puppet::Type::Datacat_fragment with Puppet::Type::Datacat_fragment failed

Change the default for goaudit::filter and goaudit::rule's 'order' parameter to
be "10"